### ISSUE TITLE
Unhandled 'error' event

### ISSUE THREAD

**Issue by tyzion** [node-pop3/node-pop3#25]
Hi,
It happened recently that testing connection with an outlook pop3 service my code kept erroring and crashing without possibility of catching the error.

The specific error is this one
`events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: Logon failure: unknown user name or bad password.
    at TLSSocket.<anonymous> (/...path/src/server/node_modules/node-pop3/lib/Connection.js:177:24)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket.EventEmitter.emit (domain.js:467:12)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at TLSSocket.Readable.push (internal/streams/readable.js:223:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)
    at Socket.ondata (internal/js_stream_socket.js:77:22)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:467:12)
Emitted 'error' event on Pop3Command instance at:
    at TLSSocket.<anonymous> (/...path/src/server/node_modules/node-pop3/lib/Connection.js:180:27)
    at TLSSocket.emit (events.js:315:20)
    [... lines matching original stack trace ...]
    at Socket.EventEmitter.emit (domain.js:467:12) {
  eventName: 'error',
  command: 'PASS ****'
}
`

kinda like the one I opened the last year, the number 18.
But this time there's not much that I can do to prevent it, I'm pretty sure.
Could you please take a look at this?

**Comment by brettz9** [comment]
Are you sure it is not a credentials change or problem with the service?

**Comment by tyzion** [comment]
Hi @brettz9, don't remember what was the issue.
I think the problem was that it threw an error which I couldn't catch (if I remember correctly only with outlook, but I'm not sure).
Right now if I use wrong user or pass the error is caught.
If the error will reappear I'll let you know 👍 
Thanks again :)
