### ISSUE TITLE
Error on `master`

### ISSUE THREAD

**Issue by brettz9** [node-pop3/node-pop3#6]
While my code is working fine on the latest npm release, on `master`, I am getting this error:

```
Error { Error: Unknown command.
    at TLSSocket.<anonymous> (/Users/brett/node-login/node_modules/node-pop3/lib/Connection.js:105:23)
    at TLSSocket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at TLSSocket.Readable.push (_stream_readable.js:224:10)
    at TLSWrap.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
    at Socket.ondata (internal/wrap_js_stream.js:64:22)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11) eventName: 'error', command: 'RETR 2' }
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: Unknown command.
    at TLSSocket.<anonymous> (/Users/brett/node-login/node_modules/node-pop3/lib/Connection.js:105:23)
    at TLSSocket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at TLSSocket.Readable.push (_stream_readable.js:224:10)
    at TLSWrap.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
    at Socket.ondata (internal/wrap_js_stream.js:64:22)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
Emitted 'error' event at:
    at TLSSocket.<anonymous> (/Users/brett/node-login/node_modules/node-pop3/lib/Connection.js:108:26)
    at TLSSocket.emit (events.js:198:13)
    [... lines matching original stack trace ...]
    at readableAddChunk (_stream_readable.js:269:11)
```

I am using `RETR` as follows:

```js
const [
    [statInfo],
    [retrInfo]
  ] = await Promise.all([
    // Get number of messages and size
    pop3.command('STAT'), // no args

    // Retrieval of message
    pop3.command('RETR', 2) // requires msg number
  ]);
```

**Comment by brettz9** [comment]
I'm not getting this error anymore, so closing.
